### ISSUE TITLE
This is an error I am geting Please help me

### ISSUE THREAD

**Issue by chethanyadav456** [JeanCarlosVR/dashboard-discord-ejs#6]
This is an error I am geting Please help me
```js (node:855) UnhandledPromiseRejectionWarning: TypeError: req.client.getRESTUser is not a function
    at /home/runner/dashboard-discord-ejs/src/routes/home/home.js:17:24
    at Layer.handle [as handle_request] (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/layer.js:95:5)
    at /home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:174:3)
    at router (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:317:13)
    at /home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/runner/dashboard-discord-ejs/node_modules/express/lib/router/index.js:275:10)
    at /home/runner/dashboard-discord-ejs/src/server.js:75:3
(Use `node --trace-warnings ...` to show where the warning was created)
(node:855) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:855) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ghost** [comment]
Bruh you cut out actual error
